import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import type { UserRole } from '../../core/auth/auth.model';
import { AuthService } from '../../core/auth/auth.service';
import type { UserProfile } from '../../core/users/users.model';
import { UsersService } from '../../core/users/users.service';

@Component({
  selector: 'app-admin', standalone: true, imports: [CommonModule, RouterLink],
  template: `<main class="admin-shell"><header><a routerLink="/dashboard">← Volver al dashboard</a><h1>Administración de usuarios</h1><p>Consulta los usuarios registrados y controla sus permisos.</p></header><section *ngIf="loading" class="state">Cargando usuarios...</section><section *ngIf="error" class="error-state"><p>{{ error }}</p><button (click)="load()">Reintentar</button></section><section *ngIf="!loading && !error" class="panel"><div class="heading"><h2>Usuarios</h2><span>{{ users.length }} registrados</span></div><div class="table-wrap"><table><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Acción</th></tr></thead><tbody><tr *ngFor="let user of users"><td><strong>{{ user.fullName }}</strong><small *ngIf="user.id === currentUserId">Tu cuenta</small></td><td>{{ user.email }}</td><td><span class="badge" [class.admin]="user.role === 'ADMIN'">{{ user.role === 'ADMIN' ? 'Administrador' : 'Usuario' }}</span></td><td><button class="role-button" [disabled]="changingId === user.id || user.id === currentUserId" (click)="toggleRole(user)">{{ changingId === user.id ? 'Guardando...' : user.role === 'ADMIN' ? 'Quitar administrador' : 'Hacer administrador' }}</button></td></tr></tbody></table></div></section></main>`,
  styles: [`:host{display:block;min-height:100vh;background:radial-gradient(circle at 5% 0,#e4e7ff,transparent 25rem),#f8f9ff;color:#18223d}.admin-shell{max-width:1080px;margin:auto;padding:40px 24px 60px}header{margin-bottom:30px}header a{color:#5146a6;font-weight:650;text-decoration:none}header a:hover{text-decoration:underline}h1{margin:18px 0 7px;font-size:2.35rem;letter-spacing:-.04em}header p{margin:0;color:#6b7590}.panel{overflow:hidden;border:1px solid #e2e4f1;border-radius:14px;background:#fff;box-shadow:0 12px 30px rgba(57,48,128,.08)}.heading{display:flex;justify-content:space-between;align-items:center;padding:22px 24px;border-bottom:1px solid #edf0f6}.heading h2{margin:0;font-size:1.2rem}.heading span{color:#727b93;font-size:.9rem}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:16px 24px;text-align:left;border-bottom:1px solid #edf0f6}th{color:#77809a;font-size:.75rem;letter-spacing:.06em;text-transform:uppercase}td{color:#45506c}td strong{display:block;color:#202b48}td small{display:block;margin-top:4px;color:#6d64b9}.badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef1f7;color:#536078;font-size:.8rem;font-weight:700}.badge.admin{background:#eeeaff;color:#5842a3}.role-button{padding:9px 12px;border:1px solid #cfc9ee;border-radius:8px;background:#fff;color:#5447a5;font:inherit;font-size:.86rem;font-weight:700;cursor:pointer}.role-button:hover:not(:disabled){background:#f5f3ff}.role-button:disabled{opacity:.55;cursor:not-allowed}.state,.error-state{padding:28px;text-align:center}.state{color:#68728e}.error-state{border-radius:12px;background:#fff1f2;color:#9f1239}.error-state button{border:0;border-radius:8px;background:#9f1239;color:#fff;padding:9px 13px;font-weight:700;cursor:pointer}@media(max-width:680px){.admin-shell{padding:28px 16px}h1{font-size:2rem}th,td{padding:14px 16px}}`],
})
export class AdminComponent implements OnInit {
  private readonly usersService = inject(UsersService); private readonly auth = inject(AuthService); private readonly cdr = inject(ChangeDetectorRef);
  protected users: UserProfile[] = []; protected loading = true; protected error = ''; protected changingId: number | null = null;
  protected get currentUserId(): number | undefined { return this.auth.getCurrentUser()?.id; }
  ngOnInit(): void { this.load(); }
  protected load(): void { this.loading = true; this.error = ''; this.usersService.list().subscribe({ next: users => { this.users = users; this.loading = false; this.cdr.detectChanges(); }, error: () => { this.error = 'No se pudo cargar la lista de usuarios.'; this.loading = false; this.cdr.detectChanges(); } }); }
  protected toggleRole(user: UserProfile): void { const role: UserRole = user.role === 'ADMIN' ? 'USER' : 'ADMIN'; this.changingId = user.id; this.usersService.updateRole(user.id, role).subscribe({ next: updated => { this.users = this.users.map(item => item.id === updated.id ? updated : item); this.changingId = null; this.cdr.detectChanges(); }, error: () => { this.error = 'No se pudo actualizar el rol.'; this.changingId = null; this.cdr.detectChanges(); } }); }
}
