import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/auth/auth.service';

@Component({
  selector: 'app-login', standalone: true, imports: [CommonModule, ReactiveFormsModule],
  template: `<main class="auth-shell"><section class="auth-layout"><div class="brand-panel"><div class="brand"><span class="brand-mark">F</span><span>FINOVA</span></div><div class="brand-copy"><p class="eyebrow">Finova Solutions</p><h1>Finanzas claras para mejores decisiones.</h1><p>Administra tus ingresos, gastos y reportes desde un solo lugar.</p></div></div><form class="auth-card" [formGroup]="form" (ngSubmit)="submit()"><div><p class="eyebrow">Acceso seguro</p><h2>Iniciar sesión</h2><p class="intro">Ingresa tus datos para continuar.</p></div><label><span>Correo electrónico</span><input type="email" formControlName="email" placeholder="correo@ejemplo.com" autocomplete="email" /></label><label><span>Contraseña</span><input type="password" formControlName="password" placeholder="Ingresa tu contraseña" autocomplete="current-password" /></label><button type="submit" [disabled]="form.invalid || isSubmitting">{{ isSubmitting ? 'Ingresando...' : 'Ingresar a Finova' }}</button><p class="error" *ngIf="errorMessage">{{ errorMessage }}</p></form></section></main>`,
  styles: [`:host{display:block;min-height:100vh;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.auth-shell{display:grid;min-height:100vh;place-items:center;padding:28px;background:radial-gradient(circle at 14% 12%,#73b8eb 0,transparent 24rem),linear-gradient(135deg,#083d73,#126bab 55%,#5aa9df)}.auth-layout{display:grid;width:min(100%,1000px);grid-template-columns:1.08fr .92fr;overflow:hidden;border:1px solid rgba(255,255,255,.28);border-radius:18px;background:#fff;box-shadow:0 22px 54px rgba(4,38,72,.27)}.brand-panel{display:flex;min-height:540px;flex-direction:column;justify-content:space-between;padding:43px;background:linear-gradient(145deg,#0b4d8d,#187bc0 62%,#65b6e6);color:#fff}.brand{display:flex;align-items:center;gap:9px;font-size:.91rem;font-weight:800;letter-spacing:.14em}.brand-mark{display:grid;width:31px;height:31px;place-items:center;border:1px solid rgba(255,255,255,.55);border-radius:9px;background:linear-gradient(145deg,rgba(255,255,255,.3),rgba(255,255,255,.04));font-size:1.15rem;font-style:italic;letter-spacing:0}.brand-copy{max-width:390px;padding-bottom:32px}.eyebrow{margin:0 0 10px;color:#94d7ff;font-size:.76rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.brand-copy h1{margin:0;color:#fff;font-size:2.35rem;line-height:1.08;letter-spacing:-.05em}.brand-copy p:last-child{margin:18px 0 0;color:rgba(255,255,255,.82);line-height:1.65}.auth-card{display:flex;flex-direction:column;justify-content:center;gap:20px;padding:46px 44px;background:linear-gradient(145deg,#fff,#f4faff)}.auth-card .eyebrow{color:#2475b7}.auth-card h2{margin:0;color:#173e66;font-size:1.72rem;letter-spacing:-.035em}.intro{margin:8px 0 0;color:#71859c}label{display:grid;gap:8px;color:#3e6080;font-size:.9rem;font-weight:750}input{min-height:46px;box-sizing:border-box;width:100%;border:1px solid #c9e1f2;border-radius:9px;padding:0 13px;background:#fff;color:#1a4269;font:inherit}input::placeholder{color:#96aabd}input:focus{outline:3px solid rgba(54,148,215,.16);border-color:#4d9fda}button{min-height:46px;margin-top:4px;border:0;border-radius:9px;background:linear-gradient(120deg,#0c5d9d,#378fd0);box-shadow:0 8px 16px rgba(18,92,154,.18);color:#fff;font:inherit;font-weight:750;cursor:pointer}button:hover:not(:disabled){filter:brightness(1.06)}button:disabled{cursor:not-allowed;opacity:.66}.error{margin:0;border-radius:8px;background:#fff1f2;padding:10px 12px;color:#ad3f4e;font-size:.9rem}@media(max-width:760px){.auth-shell{padding:16px}.auth-layout{grid-template-columns:1fr}.brand-panel{min-height:230px;padding:28px}.brand-copy{padding:30px 0 0}.brand-copy h1{font-size:1.75rem}.brand-copy p:last-child{display:none}.auth-card{padding:32px 26px}}`],
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder); private readonly authService = inject(AuthService); private readonly router = inject(Router);
  protected readonly form = this.fb.group({ email: ['', [Validators.required, Validators.email]], password: ['', Validators.required] }); protected isSubmitting = false; protected errorMessage = '';
  protected submit(): void { if (this.form.invalid) { this.form.markAllAsTouched(); this.errorMessage = 'Completa los campos requeridos.'; return; } this.isSubmitting = true; this.errorMessage = ''; this.authService.login({ email: this.form.value.email ?? '', password: this.form.value.password ?? '' }).subscribe({ next: () => this.router.navigateByUrl('/dashboard'), error: (error: HttpErrorResponse) => { this.isSubmitting = false; this.errorMessage = error.error?.error ?? 'No se pudo iniciar sesión.'; } }); }
}
