import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { formatDateSpanish, formatGuatemalanCurrency } from '../../core/dashboard/dashboard.utils';
import type { Expense, ExpenseCategory, ExpensePayload } from '../../core/expenses/expenses.model';
import { ExpensesService } from '../../core/expenses/expenses.service';

@Component({
  selector: 'app-expenses', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <main class="page-shell"><header><a routerLink="/dashboard">Volver al Dashboard</a><p class="eyebrow">Finova</p><h1>Gastos</h1><p>Registra y administra tus gastos.</p></header>
      <section class="panel"><h2>{{ editingExpense ? 'Editar gasto' : 'Nuevo gasto' }}</h2>
        <form [formGroup]="expenseForm" (ngSubmit)="saveExpense()" class="expense-form">
          <label><span>Categoría</span><select formControlName="categoryId"><option [ngValue]="null">Selecciona una categoría</option><option *ngFor="let category of categories" [ngValue]="category.id">{{ category.name }}</option></select><small *ngIf="showError('categoryId', 'required')">Selecciona una categoría.</small></label>
          <label><span>Monto</span><input type="number" min="0.01" step="0.01" formControlName="amount" placeholder="0.00" /><small *ngIf="showError('amount', 'required')">El monto es obligatorio.</small><small *ngIf="showError('amount', 'min')">El monto debe ser mayor que cero.</small></label>
          <label><span>Fecha</span><input type="date" formControlName="date" /><small *ngIf="showError('date', 'required')">La fecha es obligatoria.</small></label>
          <label><span>Descripción <em>(opcional)</em></span><textarea rows="3" formControlName="description" placeholder="Agrega un detalle"></textarea></label>
          <div class="form-actions"><button type="submit" [disabled]="isSaving">{{ isSaving ? 'Guardando...' : editingExpense ? 'Guardar cambios' : 'Guardar gasto' }}</button><button *ngIf="editingExpense" type="button" class="secondary" (click)="cancelEdit()">Cancelar</button></div>
        </form><p class="feedback success" *ngIf="successMessage">{{ successMessage }}</p><p class="feedback error" *ngIf="formError">{{ formError }}</p>
      </section>
      <section class="panel"><h2>Agregar categoría</h2><form [formGroup]="categoryForm" (ngSubmit)="addCategory()" class="category-form"><input formControlName="name" placeholder="Nombre de categoría"/><button type="submit" [disabled]="isAddingCategory">{{ isAddingCategory ? 'Agregando...' : 'Agregar categoría' }}</button></form><p class="feedback error" *ngIf="categoryError">{{ categoryError }}</p></section>
      <section class="panel"><div class="section-heading"><h2>Historial de gastos</h2><button type="button" class="secondary" (click)="loadData()" [disabled]="isLoading">Actualizar</button></div>
        <div *ngIf="isLoading" class="state">Cargando gastos...</div><div *ngIf="!isLoading && listError" class="state error-state">{{ listError }}</div><div *ngIf="!isLoading && !listError && expenses.length === 0" class="state">No hay gastos registrados.</div>
        <div *ngIf="!isLoading && !listError && expenses.length" class="table-wrapper"><table><thead><tr><th>Categoría</th><th>Monto</th><th>Fecha</th><th>Descripción</th><th>Acciones</th></tr></thead><tbody><tr *ngFor="let expense of expenses"><td>{{ expense.categoryName }}</td><td class="amount">{{ formatCurrency(expense.amount) }}</td><td>{{ formatDate(expense.date) }}</td><td>{{ expense.description || '—' }}</td><td class="actions"><button type="button" class="link" (click)="editExpense(expense)">Editar</button><button type="button" class="link danger" (click)="deleteExpense(expense)">Eliminar</button></td></tr></tbody></table></div>
      </section>
    </main>`,
  styles: [`:host{display:block;min-height:100vh;background:#f4f7fb;color:#0f172a}.page-shell{max-width:1180px;margin:auto;padding:32px 24px 56px}header{margin-bottom:28px}.eyebrow{margin:0 0 6px;color:#2563eb;font-weight:700;text-transform:uppercase;letter-spacing:.08em;font-size:.75rem}h1,h2,p{margin-top:0}h1{margin-bottom:8px;font-size:2.25rem}h2{margin-bottom:20px;font-size:1.2rem}header>p:last-child{color:#64748b;margin-bottom:0}.panel{background:#fff;border-radius:16px;box-shadow:0 4px 16px rgba(15,23,42,.07);padding:24px;margin-bottom:24px}.expense-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}label{display:flex;flex-direction:column;gap:7px;font-weight:600;color:#334155}em{font-style:normal;color:#64748b;font-weight:400}input,select,textarea{box-sizing:border-box;width:100%;border:1px solid #cbd5e1;border-radius:9px;padding:11px 12px;font:inherit;background:#fff}input:focus,select:focus,textarea:focus{outline:none;border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.13)}small{color:#b91c1c;font-weight:400}.form-actions,.section-heading,.category-form{display:flex;gap:12px;align-items:center}.section-heading{justify-content:space-between}.section-heading h2{margin:0}button{border:0;border-radius:9px;padding:11px 15px;background:#2563eb;color:#fff;font:inherit;font-weight:700;cursor:pointer}button:disabled{opacity:.65;cursor:wait}.secondary{background:#e2e8f0;color:#0f172a}.category-form input{flex:1}.feedback{margin:16px 0 0}.success{color:#047857}.error{color:#b91c1c}.state{padding:32px 0;text-align:center;color:#64748b}.error-state{color:#b91c1c}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px 10px;border-bottom:1px solid #e2e8f0;white-space:nowrap}th{color:#64748b;font-size:.78rem;text-transform:uppercase;letter-spacing:.04em}.amount{font-weight:700}.actions{display:flex;gap:10px}.link{padding:0;background:transparent;color:#2563eb}.link.danger{color:#b91c1c}@media(max-width:640px){.page-shell{padding:24px 16px}.panel{padding:20px 16px}.expense-form{grid-template-columns:1fr}.category-form{align-items:stretch;flex-direction:column}}`],
})
export class ExpensesComponent implements OnInit {
  private readonly fb = inject(FormBuilder); private readonly expensesService = inject(ExpensesService); private readonly cdr = inject(ChangeDetectorRef);
  protected readonly expenseForm = this.fb.group({ categoryId: [null as number | null, Validators.required], amount: ['', [Validators.required, Validators.min(0.01)]], date: ['', Validators.required], description: [''] });
  protected readonly categoryForm = this.fb.group({ name: ['', Validators.required] });
  protected expenses: Expense[] = []; protected categories: ExpenseCategory[] = []; protected editingExpense: Expense | null = null;
  protected isLoading = false; protected isSaving = false; protected isAddingCategory = false; protected listError = ''; protected formError = ''; protected categoryError = ''; protected successMessage = '';
  ngOnInit(): void { this.loadData(); }
  protected loadData(): void { this.isLoading = true; this.listError = ''; let expensesLoaded = false; let categoriesLoaded = false; const done = () => { if (expensesLoaded && categoriesLoaded) { this.isLoading = false; this.cdr.detectChanges(); } }; this.expensesService.list().subscribe({ next: value => { this.expenses = value; expensesLoaded = true; done(); }, error: () => { this.listError = 'No se pudieron cargar los gastos. Intenta nuevamente.'; expensesLoaded = true; done(); } }); this.expensesService.listCategories().subscribe({ next: value => { this.categories = value; categoriesLoaded = true; done(); }, error: () => { this.listError = 'No se pudieron cargar las categorías.'; categoriesLoaded = true; done(); } }); }
  protected saveExpense(): void { this.formError = ''; this.successMessage = ''; if (this.expenseForm.invalid) { this.expenseForm.markAllAsTouched(); return; } this.isSaving = true; const value = this.expenseForm.getRawValue(); const payload: ExpensePayload = { categoryId: value.categoryId!, amount: value.amount!, date: value.date!, ...(value.description?.trim() ? { description: value.description.trim() } : {}) }; const request = this.editingExpense ? this.expensesService.update(this.editingExpense.id, payload) : this.expensesService.create(payload); request.subscribe({ next: () => { this.successMessage = this.editingExpense ? 'Gasto actualizado correctamente.' : 'Gasto registrado correctamente.'; this.cancelEdit(); this.isSaving = false; this.loadData(); }, error: (error: HttpErrorResponse) => { this.formError = error.error?.error ?? 'No se pudo guardar el gasto.'; this.isSaving = false; this.cdr.detectChanges(); } }); }
  protected addCategory(): void { this.categoryError = ''; if (this.categoryForm.invalid) { this.categoryForm.markAllAsTouched(); this.categoryError = 'Ingresa el nombre de la categoría.'; return; } this.isAddingCategory = true; this.expensesService.createCategory(this.categoryForm.getRawValue().name!.trim()).subscribe({ next: category => { this.categories = [...this.categories, category].sort((a,b) => a.name.localeCompare(b.name)); this.expenseForm.patchValue({ categoryId: category.id }); this.categoryForm.reset(); this.isAddingCategory = false; this.cdr.detectChanges(); }, error: (error: HttpErrorResponse) => { this.categoryError = error.error?.error ?? 'No se pudo crear la categoría.'; this.isAddingCategory = false; this.cdr.detectChanges(); } }); }
  protected editExpense(expense: Expense): void { this.editingExpense = expense; this.expenseForm.setValue({ categoryId: expense.categoryId, amount: expense.amount, date: expense.date.slice(0,10), description: expense.description ?? '' }); this.successMessage = ''; this.formError = ''; window.scrollTo({top:0,behavior:'smooth'}); }
  protected cancelEdit(): void { this.editingExpense = null; this.expenseForm.reset({ categoryId:null, amount:'', date:'', description:'' }); }
  protected deleteExpense(expense: Expense): void { if (!window.confirm(`¿Eliminar el gasto de ${expense.categoryName}?`)) return; this.listError = ''; this.expensesService.remove(expense.id).subscribe({ next: () => { this.successMessage = 'Gasto eliminado correctamente.'; this.loadData(); }, error: (error: HttpErrorResponse) => { this.listError = error.error?.error ?? 'No se pudo eliminar el gasto.'; this.cdr.detectChanges(); } }); }
  protected showError(name: 'categoryId'|'amount'|'date', error: string): boolean { const control = this.expenseForm.get(name); return !!control && control.touched && control.hasError(error); }
  protected formatCurrency(value: string): string { return formatGuatemalanCurrency(value); } protected formatDate(value:string):string{return formatDateSpanish(value);}
}
